export const CONTEXT = {
  agentDisplayName: "agentDisplayName",
  anthropicApiKey: "anthropicApiKey",
  browserRunId: "browserRunId",
  codeRuntime: "codeRuntime",
  composioApiKey: "composioApiKey",
  composioConnectedAccounts: "composioConnectedAccounts",
  composioQuotaMeter: "composioQuotaMeter",
  composioUserId: "composioUserId",
  deepseekApiKey: "deepseekApiKey",
  exaApiKey: "exaApiKey",
  firecrawlApiKey: "firecrawlApiKey",
  globalMemory: "globalMemory",
  googleApiKey: "googleApiKey",
  llmModelId: "llmModelId",
  llmProvider: "llmProvider",
  openaiApiKey: "openaiApiKey",
  openrouterApiKey: "openrouterApiKey",
  promptProjectMode: "promptProjectMode",
  promptTaskMessage: "promptTaskMessage",
  promptWorkspaceDir: "promptWorkspaceDir",
  researchEvidenceCollector: "researchEvidenceCollector",
  researchWorkflowActive: "researchWorkflowActive",
  runIntent: "runIntent",
  userSkillCreator: "userSkillCreator",
  userSkillLoader: "userSkillLoader",
  userSkills: "userSkills",
} as const satisfies Record<string, string>;

export type ContextKey = (typeof CONTEXT)[keyof typeof CONTEXT];
