import type { ToolCapabilityName } from "@cheatcode/types";
import {
  mastraBrowserAct,
  mastraBrowserExtract,
  mastraBrowserObserve,
  mastraBrowserOpen,
  mastraBrowserScreenshot,
  mastraComposioExecute,
  mastraComposioListTools,
  mastraDataAnalyzeCsv,
  mastraDataChart,
  mastraDataScrapeToCsv,
  mastraDeepResearch,
  mastraDocsGenerateDocx,
  mastraDocsGeneratePdf,
  mastraDocsGenerateSlides,
  mastraDocsGenerateXlsx,
  mastraFirecrawlExtract,
  mastraFirecrawlScrape,
  mastraFirecrawlSearch,
  mastraFsApply,
  mastraFsDelete,
  mastraFsList,
  mastraFsRead,
  mastraFsSearch,
  mastraFsWrite,
  mastraGenerateOrEditImage,
  mastraGenerateOrExtendVideo,
  mastraGitClone,
  mastraGitCommit,
  mastraGitPush,
  mastraGitStatus,
  mastraPublishDeliverable,
  mastraResearchFanout,
  mastraRunCode,
  mastraSearchCompany,
  mastraSearchWeb,
  mastraSearchWebAdvanced,
  mastraShellExec,
  mastraShellKillProcess,
  mastraShellStartProcess,
  mastraShellTerminal,
  mastraSkillCreate,
  mastraSkillInvoke,
  mastraSkillReadReference,
  mastraStartDevServer,
} from "./registry";

type ToolRegistryContract = {
  readonly [Name in ToolCapabilityName]: { readonly id: Name };
};

export const cheatcodeTools = {
  browser_act: mastraBrowserAct,
  browser_extract: mastraBrowserExtract,
  browser_observe: mastraBrowserObserve,
  browser_open: mastraBrowserOpen,
  browser_screenshot: mastraBrowserScreenshot,
  composio_execute: mastraComposioExecute,
  composio_list_tools: mastraComposioListTools,
  data_analyze_csv: mastraDataAnalyzeCsv,
  data_chart: mastraDataChart,
  data_scrape_to_csv: mastraDataScrapeToCsv,
  deliverable_publish: mastraPublishDeliverable,
  docs_generate_docx: mastraDocsGenerateDocx,
  docs_generate_pdf: mastraDocsGeneratePdf,
  docs_generate_slides: mastraDocsGenerateSlides,
  docs_generate_xlsx: mastraDocsGenerateXlsx,
  search_extract: mastraFirecrawlExtract,
  search_scrape: mastraFirecrawlScrape,
  search_web_content: mastraFirecrawlSearch,
  fs_delete: mastraFsDelete,
  fs_apply: mastraFsApply,
  fs_list: mastraFsList,
  fs_read: mastraFsRead,
  fs_search: mastraFsSearch,
  fs_write: mastraFsWrite,
  generate_or_edit_image: mastraGenerateOrEditImage,
  generate_or_extend_video: mastraGenerateOrExtendVideo,
  git_clone: mastraGitClone,
  git_commit: mastraGitCommit,
  git_push: mastraGitPush,
  git_status: mastraGitStatus,
  research_deep: mastraDeepResearch,
  research_fanout: mastraResearchFanout,
  code_run: mastraRunCode,
  search_company: mastraSearchCompany,
  search_web: mastraSearchWeb,
  search_web_advanced: mastraSearchWebAdvanced,
  shell_exec: mastraShellExec,
  shell_kill_process: mastraShellKillProcess,
  shell_start_process: mastraShellStartProcess,
  shell_terminal: mastraShellTerminal,
  skill_create: mastraSkillCreate,
  skill_invoke: mastraSkillInvoke,
  skill_read_reference: mastraSkillReadReference,
  code_start_dev_server: mastraStartDevServer,
} as const satisfies ToolRegistryContract;
