import type {
  GenerateDocumentInput,
  GenerateSlidesInput,
  GenerateSpreadsheetInput,
} from "./schemas";

const RUNTIME_REQUIRE = [
  'import { createRequire } from "node:module";',
  'const require = createRequire("/opt/cheatcode-doc-runtime/package.json");',
].join("\n");

function assignment(name: string, value: unknown): string {
  return `const ${name} = ${JSON.stringify(value)};`;
}

function emitArtifact(filename: string, mimeType: string): string {
  return [
    "function emit(base64) {",
    "  process.stdout.write(JSON.stringify({",
    `    filename: ${JSON.stringify(filename)},`,
    `    mimeType: ${JSON.stringify(mimeType)},`,
    "    base64,",
    "  }));",
    "}",
  ].join("\n");
}

export function buildSlidesScript(input: GenerateSlidesInput, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    assignment("input", input),
    emitArtifact(
      filename,
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ),
    'const PptxGenJS = require("pptxgenjs");',
    "const pptx = new PptxGenJS();",
    'pptx.layout = "LAYOUT_WIDE";',
    'pptx.author = "Cheatcode";',
    "pptx.title = input.title;",
    "const palette = {",
    '  minimal: { bg: "FAFAFA", title: "18181B", body: "3F3F46", accent: "0F766E" },',
    '  corporate: { bg: "F8FAFC", title: "0F172A", body: "334155", accent: "2563EB" },',
    '  creative: { bg: "FFF7ED", title: "111827", body: "374151", accent: "EA580C" },',
    "}[input.theme];",
    "const titleSlide = pptx.addSlide();",
    "titleSlide.background = { color: palette.bg };",
    'titleSlide.addText(input.title, { x: 0.7, y: 2.35, w: 11.9, h: 1, fontFace: "Aptos Display", fontSize: 36, bold: true, color: palette.title, fit: "shrink" });',
    'titleSlide.addText("Generated by Cheatcode", { x: 0.75, y: 3.55, w: 6, h: 0.35, fontFace: "Aptos", fontSize: 13, color: palette.accent });',
    "for (const item of input.slides) {",
    "  const slide = pptx.addSlide();",
    "  slide.background = { color: palette.bg };",
    '  slide.addText(item.heading, { x: 0.55, y: 0.48, w: 12.2, h: 0.6, fontFace: "Aptos Display", fontSize: 26, bold: true, color: palette.title, fit: "shrink" });',
    "  slide.addShape(pptx.ShapeType.line, { x: 0.55, y: 1.26, w: 12.2, h: 0, line: { color: palette.accent, width: 1.5 } });",
    "  if (item.bullets.length > 0) {",
    '    slide.addText(item.bullets.map((text) => ({ text, options: { bullet: true } })), { x: 0.9, y: 1.65, w: 11.4, h: 4.95, fontFace: "Aptos", fontSize: 18, color: palette.body, breakLine: false, fit: "shrink" });',
    "  }",
    "  if (item.notes) { slide.addNotes(item.notes); }",
    "}",
    'const base64 = await pptx.write({ outputType: "base64" });',
    "emit(base64);",
  ].join("\n");
}

export function buildDocxScript(input: GenerateDocumentInput, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    assignment("input", input),
    emitArtifact(
      filename,
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ),
    'const { Document, HeadingLevel, Packer, Paragraph, TextRun } = require("docx");',
    "const children = [",
    "  new Paragraph({",
    "    heading: HeadingLevel.TITLE,",
    "    children: [new TextRun({ text: input.title, bold: true })],",
    "  }),",
    "];",
    "for (const section of input.sections) {",
    "  children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, text: section.heading }));",
    "  for (const paragraph of section.paragraphs) {",
    "    children.push(new Paragraph({ text: paragraph, spacing: { after: 180 } }));",
    "  }",
    "}",
    "const doc = new Document({",
    '  creator: "Cheatcode",',
    "  title: input.title,",
    "  sections: [{ children }],",
    "});",
    "const buffer = await Packer.toBuffer(doc);",
    'emit(Buffer.from(buffer).toString("base64"));',
  ].join("\n");
}

export function buildXlsxScript(input: GenerateSpreadsheetInput, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    assignment("input", input),
    emitArtifact(filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    'const ExcelJS = require("exceljs");',
    "const workbook = new ExcelJS.Workbook();",
    'workbook.creator = "Cheatcode";',
    "workbook.created = new Date();",
    "workbook.title = input.title;",
    "for (const sheet of input.sheets) {",
    "  const worksheet = workbook.addWorksheet(sheet.name);",
    "  worksheet.columns = sheet.columns.map((column) => ({",
    "    header: column,",
    "    key: column,",
    "    width: Math.max(12, Math.min(36, column.length + 8)),",
    "  }));",
    "  worksheet.addRows(sheet.rows);",
    "  worksheet.getRow(1).font = { bold: true };",
    "  worksheet.views = [{ state: 'frozen', ySplit: 1 }];",
    "}",
    "const buffer = await workbook.xlsx.writeBuffer();",
    'emit(Buffer.from(buffer).toString("base64"));',
  ].join("\n");
}

export function buildPdfScript(input: GenerateDocumentInput, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    assignment("input", input),
    emitArtifact(filename, "application/pdf"),
    'const ReactModule = await import(require.resolve("react"));',
    "const React = ReactModule.default ?? ReactModule;",
    'const renderer = await import(require.resolve("@react-pdf/renderer"));',
    "const { Document, Page, Text, StyleSheet, renderToBuffer } = renderer;",
    "const h = React.createElement;",
    "const styles = StyleSheet.create({",
    "  page: { padding: 42, fontSize: 11, color: '#18181B' },",
    "  title: { fontSize: 24, marginBottom: 18, fontWeight: 700 },",
    "  heading: { fontSize: 15, marginTop: 12, marginBottom: 6, fontWeight: 700 },",
    "  paragraph: { marginBottom: 5, lineHeight: 1.45 },",
    "});",
    "const children = [h(Text, { key: 'title', style: styles.title }, input.title)];",
    "input.sections.forEach((section, sectionIndex) => {",
    "  children.push(h(Text, { key: 'h-' + sectionIndex, style: styles.heading }, section.heading));",
    "  section.paragraphs.forEach((paragraph, paragraphIndex) => {",
    "    children.push(h(Text, { key: 'p-' + sectionIndex + '-' + paragraphIndex, style: styles.paragraph }, paragraph));",
    "  });",
    "});",
    "const document = h(Document, null, h(Page, { size: 'A4', style: styles.page }, children));",
    "const buffer = await renderToBuffer(document);",
    'emit(Buffer.from(buffer).toString("base64"));',
  ].join("\n");
}
