const RUNTIME_REQUIRE = [
  'import { createRequire } from "node:module";',
  'const require = createRequire("/opt/cheatcode-doc-runtime/package.json");',
].join("\n");

const ARTIFACT_STDOUT_MARKER = "__CHEATCODE_ARTIFACT__";

function loadInput(inputPath: string): string {
  return [
    'const { readFile } = await import("node:fs/promises");',
    `const input = JSON.parse(await readFile(${JSON.stringify(inputPath)}, "utf8"));`,
  ].join("\n");
}

function emitArtifact(filename: string, mimeType: string, outputPath: string): string {
  return [
    "async function emit(data) {",
    '  const { writeFile } = await import("node:fs/promises");',
    '  const buffer = typeof data === "string" ? Buffer.from(data, "base64") : Buffer.from(data);',
    `  await writeFile(${JSON.stringify(outputPath)}, buffer);`,
    `  process.stdout.write("\\n${ARTIFACT_STDOUT_MARKER}" + JSON.stringify({`,
    `    filename: ${JSON.stringify(filename)},`,
    `    mimeType: ${JSON.stringify(mimeType)},`,
    `    path: ${JSON.stringify(outputPath)},`,
    "  }));",
    "}",
  ].join("\n");
}

export function buildSlidesScript(inputPath: string, outputPath: string, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    loadInput(inputPath),
    emitArtifact(
      filename,
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      outputPath,
    ),
    'const PptxGenJS = require("pptxgenjs");',
    "const pptx = new PptxGenJS();",
    'pptx.layout = "LAYOUT_WIDE";',
    'pptx.author = "Cheatcode";',
    "pptx.title = input.title;",
    "const palette = {",
    '  minimal: { bg: "FAFAFA", title: "18181B", body: "3F3F46", accent: "0F766E" },',
    '  corporate: { bg: "F8FAFC", title: "0F172A", body: "334155", accent: "2563EB" },',
    '  creative: { bg: "FFF7ED", title: "111827", body: "374151", accent: "EA580C" },',
    "}[input.theme];",
    "for (const item of input.slides) {",
    "  const slide = pptx.addSlide();",
    "  slide.background = { color: palette.bg };",
    '  slide.addText(item.heading, { x: 0.55, y: 0.48, w: 12.2, h: 0.6, fontFace: "Aptos Display", fontSize: 26, bold: true, color: palette.title, fit: "shrink" });',
    "  slide.addShape(pptx.ShapeType.line, { x: 0.55, y: 1.26, w: 12.2, h: 0, line: { color: palette.accent, width: 1.5 } });",
    "  if (item.bullets.length > 0) {",
    '    slide.addText(item.bullets.map((text) => ({ text, options: { bullet: true } })), { x: 0.9, y: 1.65, w: 11.4, h: 4.95, fontFace: "Aptos", fontSize: 18, color: palette.body, breakLine: false, fit: "shrink" });',
    "  }",
    "  if (item.notes) { slide.addNotes(item.notes); }",
    "}",
    'const base64 = await pptx.write({ outputType: "base64" });',
    "await emit(base64);",
  ].join("\n");
}

export function buildDocxScript(inputPath: string, outputPath: string, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    loadInput(inputPath),
    emitArtifact(
      filename,
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      outputPath,
    ),
    'const { Document, HeadingLevel, Packer, Paragraph, TextRun } = require("docx");',
    "const children = [",
    "  new Paragraph({",
    "    heading: HeadingLevel.TITLE,",
    "    children: [new TextRun({ text: input.title, bold: true })],",
    "  }),",
    "];",
    "for (const section of input.sections) {",
    "  children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, text: section.heading }));",
    "  for (const paragraph of section.paragraphs) {",
    "    children.push(new Paragraph({ text: paragraph, spacing: { after: 180 } }));",
    "  }",
    "}",
    "const doc = new Document({",
    '  creator: "Cheatcode",',
    "  title: input.title,",
    "  sections: [{ children }],",
    "});",
    "const buffer = await Packer.toBuffer(doc);",
    "await emit(buffer);",
  ].join("\n");
}

export function buildXlsxScript(inputPath: string, outputPath: string, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    loadInput(inputPath),
    emitArtifact(
      filename,
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      outputPath,
    ),
    'const ExcelJS = require("exceljs");',
    "const workbook = new ExcelJS.Workbook();",
    'workbook.creator = "Cheatcode";',
    "workbook.created = new Date();",
    "workbook.title = input.title;",
    "for (const sheet of input.sheets) {",
    "  const worksheet = workbook.addWorksheet(sheet.name);",
    "  worksheet.columns = sheet.columns.map((column) => ({",
    "    header: column,",
    "    key: column,",
    "    width: Math.max(12, Math.min(36, column.length + 8)),",
    "  }));",
    "  worksheet.addRows(sheet.rows);",
    "  worksheet.getRow(1).font = { bold: true };",
    "  worksheet.views = [{ state: 'frozen', ySplit: 1 }];",
    "}",
    "const buffer = await workbook.xlsx.writeBuffer();",
    "await emit(buffer);",
  ].join("\n");
}

export function buildPdfScript(inputPath: string, outputPath: string, filename: string): string {
  return [
    RUNTIME_REQUIRE,
    loadInput(inputPath),
    emitArtifact(filename, "application/pdf", outputPath),
    'const ReactModule = await import(require.resolve("react"));',
    "const React = ReactModule.default ?? ReactModule;",
    'const renderer = await import(require.resolve("@react-pdf/renderer"));',
    "const { Document, Page, Text, StyleSheet, renderToBuffer } = renderer;",
    "const h = React.createElement;",
    "const styles = StyleSheet.create({",
    "  page: { padding: 42, fontSize: 11, color: '#18181B' },",
    "  title: { fontSize: 24, marginBottom: 18, fontWeight: 700 },",
    "  heading: { fontSize: 15, marginTop: 12, marginBottom: 6, fontWeight: 700 },",
    "  paragraph: { marginBottom: 5, lineHeight: 1.45 },",
    "});",
    "const children = [h(Text, { key: 'title', style: styles.title }, input.title)];",
    "input.sections.forEach((section, sectionIndex) => {",
    "  children.push(h(Text, { key: 'h-' + sectionIndex, style: styles.heading }, section.heading));",
    "  section.paragraphs.forEach((paragraph, paragraphIndex) => {",
    "    children.push(h(Text, { key: 'p-' + sectionIndex + '-' + paragraphIndex, style: styles.paragraph }, paragraph));",
    "  });",
    "});",
    "const document = h(Document, null, h(Page, { size: 'A4', style: styles.page }, children));",
    "const buffer = await renderToBuffer(document);",
    "await emit(buffer);",
  ].join("\n");
}

const MARKDOWN_PDF_SETUP = [
  'const ReactModule = await import(require.resolve("react"));',
  "const React = ReactModule.default ?? ReactModule;",
  'const renderer = await import(require.resolve("@react-pdf/renderer"));',
  "const { Document, Font, Link, Page, StyleSheet, Text, View, renderToBuffer } = renderer;",
  "const h = React.createElement;",
  "let nextKey = 0;",
  "const key = (prefix) => prefix + '-' + nextKey++;",
  "Font.register({ family: 'Liberation Sans', fonts: [",
  "  { src: '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf' },",
  "  { src: '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf', fontWeight: 700 },",
  "  { src: '/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf', fontStyle: 'italic' },",
  "  { src: '/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf', fontStyle: 'italic', fontWeight: 700 },",
  "] });",
  "Font.register({ family: 'Liberation Mono', fonts: [",
  "  { src: '/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf' },",
  "  { src: '/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf', fontWeight: 700 },",
  "] });",
].join("\n");

const MARKDOWN_PDF_STYLES = [
  "const styles = StyleSheet.create({",
  "  page: { paddingTop: 48, paddingRight: 52, paddingBottom: 56, paddingLeft: 52, fontFamily: 'Liberation Sans', fontSize: 10.5, lineHeight: 1.52, color: '#202124' },",
  "  heading1: { fontSize: 25, lineHeight: 1.18, fontWeight: 700, color: '#111318', marginTop: 2, marginBottom: 14 },",
  "  heading2: { fontSize: 18, lineHeight: 1.25, fontWeight: 700, color: '#111318', marginTop: 16, marginBottom: 8 },",
  "  heading3: { fontSize: 14, lineHeight: 1.3, fontWeight: 700, color: '#202124', marginTop: 12, marginBottom: 6 },",
  "  heading4: { fontSize: 12, lineHeight: 1.35, fontWeight: 700, color: '#202124', marginTop: 10, marginBottom: 5 },",
  "  heading5: { fontSize: 10.5, lineHeight: 1.4, fontWeight: 700, color: '#3C4043', marginTop: 8, marginBottom: 4 },",
  "  heading6: { fontSize: 9.5, lineHeight: 1.4, fontWeight: 700, color: '#5F6368', marginTop: 7, marginBottom: 4 },",
  "  paragraph: { marginBottom: 9 },",
  "  compactParagraph: { marginBottom: 3 },",
  "  strong: { fontWeight: 700 },",
  "  emphasis: { fontStyle: 'italic' },",
  "  deleted: { textDecoration: 'line-through', color: '#5F6368' },",
  "  link: { color: '#1659A7', textDecoration: 'underline' },",
  "  inlineCode: { fontFamily: 'Liberation Mono', fontSize: 9.2, backgroundColor: '#F1F3F4', color: '#202124' },",
  "  codeBlock: { fontFamily: 'Liberation Mono', fontSize: 8.5, lineHeight: 1.45, color: '#202124', backgroundColor: '#F6F8FA', borderColor: '#DADCE0', borderWidth: 0.75, borderRadius: 3, padding: 9, marginTop: 2, marginBottom: 10 },",
  "  blockquote: { borderLeftColor: '#9AA0A6', borderLeftWidth: 2, paddingLeft: 10, color: '#4B4F52', marginTop: 2, marginBottom: 9 },",
  "  list: { marginBottom: 7 },",
  "  listRow: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', marginBottom: 3 },",
  "  listMarker: { width: 22, flexShrink: 0, paddingRight: 5, textAlign: 'right' },",
  "  listBody: { flexGrow: 1, flexShrink: 1 },",
  "  rule: { borderBottomColor: '#DADCE0', borderBottomWidth: 0.75, marginTop: 8, marginBottom: 12 },",
  "  table: { borderColor: '#C7C9CC', borderTopWidth: 0.75, borderLeftWidth: 0.75, marginTop: 3, marginBottom: 11 },",
  "  tableRow: { flexDirection: 'row', borderBottomColor: '#C7C9CC', borderBottomWidth: 0.75 },",
  "  tableHeader: { backgroundColor: '#F1F3F4' },",
  "  tableCell: { flexGrow: 1, flexBasis: 0, borderRightColor: '#C7C9CC', borderRightWidth: 0.75, paddingTop: 5, paddingRight: 5, paddingBottom: 5, paddingLeft: 5 },",
  "  tableText: { fontSize: 8.2, lineHeight: 1.35 },",
  "  tableHeaderText: { fontWeight: 700, color: '#202124' },",
  "});",
].join("\n");

const MARKDOWN_PDF_INLINE_RENDERER = [
  "function safeUrl(value) {",
  "  return typeof value === 'string' && /^(?:https?:|mailto:)/i.test(value) ? value : undefined;",
  "}",
  "function plainHtml(value) {",
  "  return String(value ?? '').replace(/<[^>]*>/g, '').trim();",
  "}",
  "function renderInline(tokens) {",
  "  const children = [];",
  "  for (const token of tokens ?? []) {",
  "    const nested = () => renderInline(token.tokens ?? []);",
  "    if (token.type === 'text' || token.type === 'escape') children.push(token.tokens ? nested() : token.text);",
  "    else if (token.type === 'strong') children.push(h(Text, { key: key('strong'), style: styles.strong }, nested()));",
  "    else if (token.type === 'em') children.push(h(Text, { key: key('em'), style: styles.emphasis }, nested()));",
  "    else if (token.type === 'del') children.push(h(Text, { key: key('del'), style: styles.deleted }, nested()));",
  "    else if (token.type === 'codespan') children.push(h(Text, { key: key('code'), style: styles.inlineCode }, token.text));",
  "    else if (token.type === 'link') { const url = safeUrl(token.href); children.push(url ? h(Link, { key: key('link'), src: url, style: styles.link }, nested()) : h(Text, { key: key('link-text') }, nested())); }",
  "    else if (token.type === 'image') { const label = '[Image: ' + (token.text || token.href) + ']'; const url = safeUrl(token.href); children.push(url ? h(Link, { key: key('image'), src: url, style: styles.link }, label) : label); }",
  "    else if (token.type === 'br') children.push('\\n');",
  "    else if (token.type === 'checkbox') children.push(token.checked ? '[x] ' : '[ ] ');",
  "    else if (token.type === 'html') children.push(plainHtml(token.text));",
  "    else if (token.tokens) children.push(nested());",
  "    else if (typeof token.text === 'string') children.push(token.text);",
  "  }",
  "  return children.flat();",
  "}",
].join("\n");

const MARKDOWN_PDF_BLOCK_RENDERER = [
  "const noHyphenation = (word) => [word];",
  "function shouldKeepListTogether(token) {",
  "  const sourceLength = typeof token.raw === 'string' ? token.raw.length : 0;",
  "  return token.items.length <= 6 && sourceLength <= 900;",
  "}",
  "function nextRenderableToken(tokens, index) {",
  "  for (let nextIndex = index + 1; nextIndex < tokens.length; nextIndex += 1) {",
  "    const token = tokens[nextIndex];",
  "    if (token.type !== 'space' && token.type !== 'def') return token;",
  "  }",
  "  return undefined;",
  "}",
  "function headingPresenceAhead(nextToken) {",
  "  if (nextToken?.type === 'list' && shouldKeepListTogether(nextToken)) {",
  "    return Math.min(150, 42 + nextToken.items.length * 18);",
  "  }",
  "  return 60;",
  "}",
  "function renderList(token, depth = 0) {",
  "  const start = Number.isFinite(Number(token.start)) ? Number(token.start) : 1;",
  "  const rows = token.items.map((item, index) => {",
  "    const nestedLists = item.tokens.filter((child) => child.type === 'list');",
  "    const bodyTokens = item.tokens.filter((child) => child.type !== 'list');",
  "    const marker = item.task ? (item.checked ? '[x]' : '[ ]') : token.ordered ? String(start + index) + '.' : '•';",
  "    return h(View, { key: key('item'), style: styles.listRow, wrap: false },",
  "      h(Text, { style: styles.listMarker }, marker),",
  "      h(View, { style: styles.listBody }, renderBlocks(bodyTokens, true), nestedLists.map((list) => renderList(list, depth + 1))),",
  "    );",
  "  });",
  "  return h(View, { key: key('list'), style: [styles.list, { marginLeft: Math.min(depth, 3) * 9 }], wrap: !shouldKeepListTogether(token) }, rows);",
  "}",
  "function renderTable(token) {",
  "  const rows = [token.header, ...token.rows];",
  "  return h(View, { key: key('table'), style: styles.table }, rows.map((row, rowIndex) =>",
  "    h(View, { key: key('row'), style: [styles.tableRow, rowIndex === 0 ? styles.tableHeader : null], wrap: false }, row.map((cell, cellIndex) =>",
  "      h(View, { key: key('cell'), style: [styles.tableCell, cellIndex === row.length - 1 ? { borderRightWidth: 0 } : null] },",
  "        h(Text, { style: [styles.tableText, rowIndex === 0 ? styles.tableHeaderText : null, { textAlign: cell.align ?? 'left' }] }, renderInline(cell.tokens)),",
  "      ),",
  "    )),",
  "  ));",
  "}",
  "function renderBlocks(tokens, compact = false) {",
  "  const blocks = [];",
  "  const renderableTokens = tokens ?? [];",
  "  for (let tokenIndex = 0; tokenIndex < renderableTokens.length; tokenIndex += 1) {",
  "    const token = renderableTokens[tokenIndex];",
  "    if (token.type === 'space' || token.type === 'def') continue;",
  "    if (token.type === 'heading') blocks.push(h(Text, { hyphenationCallback: noHyphenation, key: key('heading'), minPresenceAhead: headingPresenceAhead(nextRenderableToken(renderableTokens, tokenIndex)), style: styles['heading' + Math.min(token.depth, 6)], wrap: false }, renderInline(token.tokens)));",
  "    else if (token.type === 'paragraph' || token.type === 'text') blocks.push(h(Text, { key: key('paragraph'), orphans: 2, style: compact ? styles.compactParagraph : styles.paragraph, widows: 2 }, renderInline(token.tokens ?? [token])));",
  "    else if (token.type === 'code') blocks.push(h(Text, { key: key('codeblock'), style: styles.codeBlock }, token.text));",
  "    else if (token.type === 'blockquote') blocks.push(h(View, { key: key('quote'), style: styles.blockquote }, renderBlocks(token.tokens, true)));",
  "    else if (token.type === 'list') blocks.push(renderList(token));",
  "    else if (token.type === 'table') blocks.push(renderTable(token));",
  "    else if (token.type === 'hr') blocks.push(h(View, { key: key('rule'), style: styles.rule }));",
  "    else if (token.type === 'html') { const text = plainHtml(token.text); if (text) blocks.push(h(Text, { key: key('html'), style: styles.paragraph }, text)); }",
  "    else if (token.tokens) blocks.push(...renderBlocks(token.tokens, compact));",
  "  }",
  "  return blocks;",
  "}",
].join("\n");

const MARKDOWN_PDF_DOCUMENT = [
  "const document = h(Document, { author: 'Cheatcode', subject: 'Research report', title: input.title },",
  "  h(Page, { size: 'A4', style: styles.page, wrap: true },",
  "    ...renderBlocks(input.tokens),",
  "  ),",
  ");",
  "const buffer = await renderToBuffer(document);",
  "await emit(buffer);",
].join("\n");

export function buildMarkdownPdfScript(
  inputPath: string,
  outputPath: string,
  filename: string,
): string {
  return [
    RUNTIME_REQUIRE,
    loadInput(inputPath),
    emitArtifact(filename, "application/pdf", outputPath),
    MARKDOWN_PDF_SETUP,
    MARKDOWN_PDF_STYLES,
    MARKDOWN_PDF_INLINE_RENDERER,
    MARKDOWN_PDF_BLOCK_RENDERER,
    MARKDOWN_PDF_DOCUMENT,
  ].join("\n");
}
