import { accountRoutes, accountSchemas } from "./openapi-account-routes";
import { billingRoutes, billingSchemas } from "./openapi-billing-routes";
import {
  arrayOf,
  buildOpenApiDocument,
  emptyResponse,
  type JsonValue,
  jsonBody,
  jsonResponse,
  nullableNumberSchema,
  nullableStringSchema,
  type OpenApiRoute,
  recordOf,
  renderOpenApiDocsHtml,
  schemaRef,
  stringSchema,
} from "./openapi-builder";
import { discoveryRoutes, discoverySchemas } from "./openapi-discovery-routes";
import { runControlRoutes, runControlSchemas } from "./openapi-run-control-routes";
import { sandboxRoutes, sandboxSchemas } from "./openapi-sandbox-routes";
import {
  arraySchemaFor,
  idempotencyKeyParameter,
  objectSchemaFor,
  paginatedSchemaFor,
  paginationParameters,
} from "./openapi-schema-utils";

const PROVIDER_SCHEMA: JsonValue = {
  enum: [
    "anthropic",
    "openai",
    "google",
    "openrouter",
    "deepseek",
    "exa",
    "firecrawl",
    "llamaparse",
  ],
  type: "string",
};

const COMPONENT_SCHEMAS: { [name: string]: JsonValue } = {
  Agent: {
    additionalProperties: false,
    properties: {
      description: stringSchema(),
      name: stringSchema(),
    },
    required: ["description", "name"],
    type: "object",
  },
  ClientError: {
    additionalProperties: false,
    properties: {
      message: stringSchema({ maxLength: 2_000 }),
      stack: stringSchema({ maxLength: 8_000 }),
      timestamp: { minimum: 0, type: "integer" },
      type: stringSchema({ maxLength: 120 }),
      url: stringSchema({ maxLength: 2_000 }),
      userAgent: stringSchema({ maxLength: 1_000 }),
    },
    type: "object",
  },
  ClientUserEvent: {
    additionalProperties: false,
    properties: {
      eventName: { enum: ["first_preview_opened"], type: "string" },
    },
    required: ["eventName"],
    type: "object",
  },
  CreateProject: {
    additionalProperties: false,
    properties: {
      budgetCapUsd: { exclusiveMinimum: 0, maximum: 50, type: "number" },
      defaultModel: stringSchema({ maxLength: 200, minLength: 1 }),
      importRepoUrl: stringSchema({ format: "uri", maxLength: 300 }),
      masterInstructions: stringSchema({ maxLength: 20_000 }),
      mode: {
        default: "general",
        enum: ["app-builder", "app-builder-mobile", "general"],
        type: "string",
      },
      name: stringSchema({ maxLength: 120, minLength: 1 }),
    },
    required: ["name"],
    type: "object",
  },
  CreateRun: {
    additionalProperties: false,
    properties: {
      agentName: stringSchema(),
      budgetCapUsd: { exclusiveMinimum: 0, maximum: 50, type: "number" },
      message: {
        additionalProperties: false,
        properties: {
          id: stringSchema(),
          parts: arrayOf(schemaRef("MessagePart")),
          role: { const: "user" },
        },
        required: ["parts", "role"],
        type: "object",
      },
      model: stringSchema(),
    },
    required: ["message"],
    type: "object",
  },
  CreateThread: {
    additionalProperties: false,
    properties: {
      defaultModel: stringSchema({ maxLength: 200, minLength: 1 }),
      importRepoUrl: stringSchema({ maxLength: 300, minLength: 1 }),
      initialPrompt: stringSchema({ maxLength: 20_000, minLength: 1 }),
      mode: { enum: ["app-builder", "app-builder-mobile", "general"], type: "string" },
      projectId: stringSchema({ format: "uuid" }),
      title: stringSchema({ maxLength: 200, minLength: 1 }),
    },
    type: "object",
  },
  Error: {
    additionalProperties: false,
    properties: {
      error: {
        additionalProperties: true,
        properties: {
          code: stringSchema(),
          details: { type: "object" },
          doc_url: stringSchema({ format: "uri" }),
          hint: stringSchema(),
          message: stringSchema(),
          request_id: stringSchema(),
          retriable: { type: "boolean" },
        },
        required: ["code", "message", "request_id", "retriable"],
        type: "object",
      },
    },
    required: ["error"],
    type: "object",
  },
  Health: {
    additionalProperties: true,
    properties: {
      ok: { type: "boolean" },
      service: stringSchema(),
    },
    required: ["ok"],
    type: "object",
  },
  Integration: {
    additionalProperties: false,
    properties: {
      connectedAt: nullableStringSchema({ format: "date-time" }),
      connectionId: nullableStringSchema(),
      displayName: stringSchema(),
      name: { pattern: "^[a-z0-9_]+$", type: "string" },
      status: {
        enum: ["not_connected", "initiating", "active", "inactive", "expired", "failed"],
        type: "string",
      },
      updatedAt: nullableStringSchema({ format: "date-time" }),
    },
    required: ["connectedAt", "connectionId", "displayName", "name", "status", "updatedAt"],
    type: "object",
  },
  IntegrationCatalog: {
    additionalProperties: false,
    properties: {
      categories: arrayOf(schemaRef("ToolkitCategory")),
      toolkits: arrayOf(schemaRef("ToolkitCatalogEntry")),
    },
    required: ["categories", "toolkits"],
    type: "object",
  },
  IntegrationConnect: {
    additionalProperties: false,
    properties: {
      oauthUrl: stringSchema({ format: "uri" }),
    },
    required: ["oauthUrl"],
    type: "object",
  },
  ToolkitAction: {
    additionalProperties: false,
    properties: {
      description: stringSchema(),
      name: stringSchema(),
      slug: stringSchema(),
    },
    required: ["description", "name", "slug"],
    type: "object",
  },
  ToolkitActionsResponse: {
    additionalProperties: false,
    properties: {
      actions: arrayOf(schemaRef("ToolkitAction")),
    },
    required: ["actions"],
    type: "object",
  },
  ToolkitCatalogEntry: {
    additionalProperties: false,
    properties: {
      categorySlugs: arrayOf(stringSchema()),
      connectable: { type: "boolean" },
      connectedAt: nullableStringSchema({ format: "date-time" }),
      description: stringSchema(),
      displayName: stringSchema(),
      name: { pattern: "^[a-z0-9_]+$", type: "string" },
      status: {
        enum: ["not_connected", "initiating", "active", "inactive", "expired", "failed"],
        type: "string",
      },
      updatedAt: nullableStringSchema({ format: "date-time" }),
    },
    required: [
      "categorySlugs",
      "connectable",
      "connectedAt",
      "description",
      "displayName",
      "name",
      "status",
      "updatedAt",
    ],
    type: "object",
  },
  ToolkitCategory: {
    additionalProperties: false,
    properties: {
      name: stringSchema(),
      slug: stringSchema(),
    },
    required: ["name", "slug"],
    type: "object",
  },
  LimitsSnapshot: {
    additionalProperties: false,
    properties: {
      quotas: recordOf({
        additionalProperties: false,
        properties: {
          limit: { type: "number" },
          period_end: stringSchema(),
          used: { type: "number" },
        },
        required: ["limit", "period_end", "used"],
        type: "object",
      }),
      rate_limits: recordOf({
        additionalProperties: false,
        properties: {
          limit: { type: "number" },
          remaining: { type: "number" },
          reset_at: { type: "number" },
        },
        required: ["limit", "remaining", "reset_at"],
        type: "object",
      }),
    },
    required: ["quotas", "rate_limits"],
    type: "object",
  },
  MessagePart: {
    additionalProperties: true,
    properties: {
      type: stringSchema(),
    },
    required: ["type"],
    type: "object",
  },
  Ok: {
    additionalProperties: false,
    properties: {
      ok: { type: "boolean" },
    },
    required: ["ok"],
    type: "object",
  },
  OpenApiDocument: {
    additionalProperties: true,
    properties: {
      openapi: stringSchema(),
    },
    required: ["openapi"],
    type: "object",
  },
  OpenSandboxTerminal: {
    additionalProperties: false,
    properties: {
      command: stringSchema({ maxLength: 2_000, minLength: 1 }),
      cwd: stringSchema({ maxLength: 1_000, minLength: 1 }),
      timeoutMs: { maximum: 60_000, minimum: 1, type: "integer" },
    },
    required: ["command"],
    type: "object",
  },
  Project: {
    additionalProperties: false,
    properties: {
      archiveAfter: nullableStringSchema({ format: "date-time" }),
      archivedPendingAction: { type: "boolean" },
      budgetCapUsd: nullableNumberSchema({ exclusiveMinimum: 0, maximum: 50 }),
      createdAt: stringSchema({ format: "date-time" }),
      defaultModel: nullableStringSchema({ maxLength: 200, minLength: 1 }),
      id: stringSchema({ format: "uuid" }),
      importRepoUrl: nullableStringSchema({ maxLength: 300 }),
      masterInstructions: nullableStringSchema(),
      mode: stringSchema(),
      name: stringSchema(),
      overQuota: { type: "boolean" },
      readOnly: { type: "boolean" },
      updatedAt: stringSchema({ format: "date-time" }),
    },
    required: [
      "archiveAfter",
      "archivedPendingAction",
      "budgetCapUsd",
      "createdAt",
      "defaultModel",
      "id",
      "masterInstructions",
      "mode",
      "name",
      "overQuota",
      "readOnly",
      "updatedAt",
    ],
    type: "object",
  },
  ProviderKeySummary: {
    additionalProperties: false,
    properties: {
      disabledAt: nullableStringSchema({ format: "date-time" }),
      disabledReason: nullableStringSchema(),
      fingerprint: stringSchema(),
      lastUsedAt: nullableStringSchema(),
      provider: PROVIDER_SCHEMA,
    },
    required: ["disabledAt", "disabledReason", "fingerprint", "lastUsedAt", "provider"],
    type: "object",
  },
  ResumeTakeover: {
    additionalProperties: false,
    properties: {
      resumeToken: stringSchema({ minLength: 1 }),
    },
    required: ["resumeToken"],
    type: "object",
  },
  RunStatus: {
    additionalProperties: true,
    properties: {
      active: { type: "boolean" },
      error: { type: ["object", "null"] },
      pendingApproval: {
        additionalProperties: false,
        properties: {
          approvalId: stringSchema({ format: "uuid" }),
          expiresAt: { type: "integer" },
          kind: { enum: ["tool-approval", "model-fallback"], type: "string" },
          requestedAt: { type: "integer" },
          summary: stringSchema(),
          timeoutDecision: { enum: ["allow", "deny"], type: "string" },
          toolName: stringSchema(),
        },
        required: ["approvalId", "expiresAt", "kind", "requestedAt", "summary", "timeoutDecision"],
        type: "object",
      },
      previewUrl: nullableStringSchema({ format: "uri" }),
      runId: nullableStringSchema(),
      status: {
        enum: ["idle", "running", "paused", "completed", "failed", "canceled", null],
        type: ["string", "null"],
      },
    },
    type: "object",
  },
  SandboxFile: {
    additionalProperties: false,
    properties: {
      content: stringSchema(),
      encoding: { enum: ["utf8", "base64"], type: "string" },
      key: stringSchema(),
      path: stringSchema(),
    },
    required: ["content", "encoding", "path"],
    type: "object",
  },
  SandboxFileList: {
    additionalProperties: false,
    properties: {
      files: arrayOf({
        additionalProperties: false,
        properties: {
          modifiedAt: stringSchema(),
          name: stringSchema(),
          path: stringSchema(),
          relativePath: stringSchema(),
          size: { minimum: 0, type: "integer" },
          type: { enum: ["file", "directory", "symlink", "other"], type: "string" },
        },
        required: ["modifiedAt", "name", "path", "relativePath", "size", "type"],
        type: "object",
      }),
      path: stringSchema(),
    },
    required: ["files", "path"],
    type: "object",
  },
  SandboxFileWrite: {
    additionalProperties: false,
    properties: {
      path: stringSchema(),
      success: { type: "boolean" },
    },
    required: ["path", "success"],
    type: "object",
  },
  TakeoverSession: {
    additionalProperties: false,
    properties: {
      resumeToken: stringSchema(),
      vncUrl: stringSchema({ format: "uri" }),
    },
    required: ["resumeToken", "vncUrl"],
    type: "object",
  },
  TerminalPreview: {
    additionalProperties: false,
    properties: {
      command: stringSchema(),
      cwd: stringSchema({ maxLength: 1_000, minLength: 1 }),
      durationMs: { minimum: 0, type: "integer" },
      exitCode: { type: "integer" },
      stderr: stringSchema(),
      stdout: stringSchema(),
      success: { type: "boolean" },
    },
    required: ["command", "exitCode", "stderr", "stdout", "success"],
    type: "object",
  },
  TerminalContext: {
    additionalProperties: false,
    properties: {
      cwd: stringSchema({ maxLength: 1_000, minLength: 1 }),
      displayCwd: stringSchema({ maxLength: 1_000, minLength: 1 }),
      displayWorkspacePath: stringSchema({ maxLength: 200, minLength: 1 }),
      host: stringSchema({ maxLength: 200, minLength: 1 }),
    },
    required: ["cwd", "displayCwd", "displayWorkspacePath", "host"],
    type: "object",
  },
  Thread: {
    additionalProperties: false,
    properties: {
      activeRunId: nullableStringSchema({ format: "uuid" }),
      createdAt: stringSchema({ format: "date-time" }),
      id: stringSchema({ format: "uuid" }),
      projectId: nullableStringSchema({ format: "uuid" }),
      title: nullableStringSchema(),
      updatedAt: stringSchema({ format: "date-time" }),
    },
    required: ["activeRunId", "createdAt", "id", "projectId", "title", "updatedAt"],
    type: "object",
  },
  Tool: {
    additionalProperties: false,
    properties: {
      description: stringSchema(),
      domain: stringSchema(),
      name: stringSchema(),
    },
    required: ["description", "domain", "name"],
    type: "object",
  },
  UIMessage: {
    additionalProperties: false,
    properties: {
      agentRunId: nullableStringSchema({ format: "uuid" }),
      createdAt: stringSchema({ format: "date-time" }),
      id: stringSchema({ format: "uuid" }),
      parts: arrayOf(schemaRef("MessagePart")),
      role: stringSchema(),
      threadId: stringSchema({ format: "uuid" }),
    },
    required: ["agentRunId", "createdAt", "id", "parts", "role", "threadId"],
    type: "object",
  },
  User: {
    additionalProperties: false,
    properties: {
      userId: stringSchema({ format: "uuid" }),
    },
    required: ["userId"],
    type: "object",
  },
  UpdateProject: {
    additionalProperties: false,
    minProperties: 1,
    properties: {
      budgetCapUsd: nullableNumberSchema({ exclusiveMinimum: 0, maximum: 50 }),
      defaultModel: nullableStringSchema({ maxLength: 200, minLength: 1 }),
      importRepoUrl: nullableStringSchema({ maxLength: 300 }),
      masterInstructions: nullableStringSchema({ maxLength: 20_000 }),
      name: stringSchema({ maxLength: 120, minLength: 1 }),
    },
    type: "object",
  },
  UpsertProviderKey: {
    additionalProperties: false,
    properties: {
      key: stringSchema({ maxLength: 20_000, minLength: 1 }),
      provider: PROVIDER_SCHEMA,
    },
    required: ["key", "provider"],
    type: "object",
  },
  WebVitals: {
    oneOf: [schemaRef("WebVitalsMetric"), arrayOf(schemaRef("WebVitalsMetric"))],
  },
  WebVitalsMetric: {
    additionalProperties: false,
    properties: {
      attributionTarget: stringSchema({ maxLength: 1_000 }),
      delta: { type: "number" },
      id: stringSchema({ maxLength: 200 }),
      name: stringSchema({ maxLength: 40 }),
      navigationType: stringSchema({ maxLength: 80 }),
      rating: { enum: ["good", "needs-improvement", "poor"], type: "string" },
      url: stringSchema({ maxLength: 2_000 }),
      value: { type: "number" },
    },
    required: ["id", "name", "value"],
    type: "object",
  },
  WriteSandboxFile: {
    additionalProperties: false,
    properties: {
      content: stringSchema({ maxLength: 2_000_000 }),
      encoding: { default: "utf8", enum: ["utf8", "base64"], type: "string" },
      path: stringSchema(),
    },
    required: ["content"],
    type: "object",
  },
};

const objectSchema = (name: string): JsonValue => objectSchemaFor(COMPONENT_SCHEMAS, name);
const arraySchema = (name: string): JsonValue => arraySchemaFor(COMPONENT_SCHEMAS, name);
const paginatedSchema = (name: string): JsonValue => paginatedSchemaFor(COMPONENT_SCHEMAS, name);

const routes: OpenApiRoute[] = [
  ...accountRoutes,
  ...discoveryRoutes,
  {
    method: "get",
    operationId: "listProjects",
    parameters: paginationParameters,
    path: "/v1/projects",
    responses: { "200": jsonResponse("Projects", paginatedSchema("Project")) },
    security: [{ bearerAuth: [] }],
    summary: "List projects",
    tags: ["projects"],
  },
  {
    method: "post",
    operationId: "createProject",
    path: "/v1/projects",
    requestBody: jsonBody(objectSchema("CreateProject")),
    responses: { "201": jsonResponse("Created project", objectSchema("Project")) },
    security: [{ bearerAuth: [] }],
    summary: "Create a project",
    tags: ["projects"],
  },
  {
    method: "get",
    operationId: "getProject",
    path: "/v1/projects/{projectId}",
    responses: {
      "200": jsonResponse("Project", objectSchema("Project")),
      "404": jsonResponse("Not found", objectSchema("Error")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Get a project",
    tags: ["projects"],
  },
  {
    method: "patch",
    operationId: "updateProject",
    path: "/v1/projects/{projectId}",
    requestBody: jsonBody(objectSchema("UpdateProject")),
    responses: { "200": jsonResponse("Updated project", objectSchema("Project")) },
    security: [{ bearerAuth: [] }],
    summary: "Update a project",
    tags: ["projects"],
  },
  {
    method: "delete",
    operationId: "deleteProject",
    path: "/v1/projects/{projectId}",
    responses: { "204": emptyResponse("Project archived") },
    security: [{ bearerAuth: [] }],
    summary: "Archive a project",
    tags: ["projects"],
  },
  {
    method: "get",
    operationId: "listProjectThreads",
    parameters: paginationParameters,
    path: "/v1/projects/{projectId}/threads",
    responses: { "200": jsonResponse("Threads", paginatedSchema("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "List project threads",
    tags: ["threads"],
  },
  {
    method: "post",
    operationId: "createThread",
    path: "/v1/projects/{projectId}/threads",
    requestBody: jsonBody(objectSchema("CreateThread")),
    responses: { "201": jsonResponse("Created thread", objectSchema("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "Create a thread",
    tags: ["threads"],
  },
  {
    method: "get",
    operationId: "getThread",
    path: "/v1/threads/{threadId}",
    responses: { "200": jsonResponse("Thread", objectSchema("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "Get a thread",
    tags: ["threads"],
  },
  {
    method: "get",
    operationId: "listThreadMessages",
    parameters: paginationParameters,
    path: "/v1/threads/{threadId}/messages",
    responses: { "200": jsonResponse("Messages", paginatedSchema("UIMessage")) },
    security: [{ bearerAuth: [] }],
    summary: "List thread messages",
    tags: ["threads"],
  },
  {
    method: "post",
    operationId: "createThreadRun",
    parameters: [idempotencyKeyParameter],
    path: "/v1/threads/{threadId}/runs",
    requestBody: jsonBody(objectSchema("CreateRun")),
    responses: { "202": emptyResponse("UIMessage SSE stream") },
    security: [{ bearerAuth: [] }],
    summary: "Start an agent run",
    tags: ["runs"],
  },
  {
    method: "get",
    operationId: "resumeThreadRunStream",
    path: "/v1/threads/{threadId}/runs/stream",
    responses: {
      "200": emptyResponse("UIMessage SSE stream"),
      "204": emptyResponse("No active stream"),
    },
    security: [{ bearerAuth: [] }],
    summary: "Resume an agent run stream",
    tags: ["runs"],
  },
  {
    method: "get",
    operationId: "getThreadRunStatus",
    path: "/v1/threads/{threadId}/runs/status",
    responses: {
      "200": jsonResponse("Run status", objectSchema("RunStatus")),
      "204": emptyResponse("No active run"),
    },
    security: [{ bearerAuth: [] }],
    summary: "Get active run status for a thread",
    tags: ["runs"],
  },
  {
    method: "post",
    operationId: "cancelRun",
    path: "/v1/runs/{runId}/cancel",
    responses: { "200": jsonResponse("Cancellation accepted", objectSchema("Ok")) },
    security: [{ bearerAuth: [] }],
    summary: "Cancel an agent run",
    tags: ["runs"],
  },
  ...runControlRoutes,
  {
    method: "post",
    operationId: "startRunTakeover",
    path: "/v1/runs/{runId}/takeover",
    responses: { "200": jsonResponse("Takeover URL", objectSchema("TakeoverSession")) },
    security: [{ bearerAuth: [] }],
    summary: "Start browser takeover",
    tags: ["runs"],
  },
  {
    method: "post",
    operationId: "resumeRunAfterTakeover",
    path: "/v1/runs/{runId}/resume",
    requestBody: jsonBody(objectSchema("ResumeTakeover")),
    responses: { "200": jsonResponse("Resume accepted", objectSchema("Ok")) },
    security: [{ bearerAuth: [] }],
    summary: "Resume after browser takeover",
    tags: ["runs"],
  },
  {
    method: "get",
    operationId: "downloadOutput",
    path: "/v1/outputs/{outputId}/download",
    responses: {
      "200": emptyResponse("Signed output file"),
      "410": jsonResponse("Expired", objectSchema("Error")),
    },
    summary: "Download a signed generated output",
    tags: ["outputs"],
  },
  {
    method: "get",
    operationId: "listTools",
    path: "/v1/tools",
    responses: { "200": jsonResponse("Tools", arraySchema("Tool")) },
    security: [{ bearerAuth: [] }],
    summary: "List tools",
    tags: ["metadata"],
  },
  {
    method: "get",
    operationId: "listAgents",
    path: "/v1/agents",
    responses: { "200": jsonResponse("Agents", arraySchema("Agent")) },
    security: [{ bearerAuth: [] }],
    summary: "List agents",
    tags: ["metadata"],
  },
  ...sandboxRoutes,
  {
    method: "get",
    operationId: "listIntegrations",
    path: "/v1/integrations",
    responses: { "200": jsonResponse("Integrations", arraySchema("Integration")) },
    security: [{ bearerAuth: [] }],
    summary: "List Composio integrations",
    tags: ["integrations"],
  },
  {
    method: "get",
    operationId: "getIntegrationCatalog",
    path: "/v1/integrations/catalog",
    responses: { "200": jsonResponse("Catalog", objectSchema("IntegrationCatalog")) },
    security: [{ bearerAuth: [] }],
    summary: "Browse the Composio toolkit catalog with per-user connection status",
    tags: ["integrations"],
  },
  {
    method: "get",
    operationId: "listToolkitActions",
    path: "/v1/integrations/{name}/tools",
    responses: { "200": jsonResponse("Toolkit actions", objectSchema("ToolkitActionsResponse")) },
    security: [{ bearerAuth: [] }],
    summary: "List a toolkit's available actions",
    tags: ["integrations"],
  },
  {
    method: "post",
    operationId: "connectIntegration",
    path: "/v1/integrations/{name}/connect",
    responses: { "200": jsonResponse("OAuth URL", objectSchema("IntegrationConnect")) },
    security: [{ bearerAuth: [] }],
    summary: "Start integration OAuth",
    tags: ["integrations"],
  },
  {
    method: "delete",
    operationId: "deleteIntegration",
    path: "/v1/integrations/{name}",
    responses: { "204": emptyResponse("Integration deleted") },
    security: [{ bearerAuth: [] }],
    summary: "Delete integration",
    tags: ["integrations"],
  },
  {
    method: "get",
    operationId: "listProviderKeys",
    path: "/v1/provider-keys",
    responses: { "200": jsonResponse("Provider keys", arraySchema("ProviderKeySummary")) },
    security: [{ bearerAuth: [] }],
    summary: "List BYOK provider keys",
    tags: ["byok"],
  },
  {
    method: "post",
    operationId: "upsertProviderKey",
    path: "/v1/provider-keys",
    requestBody: jsonBody(objectSchema("UpsertProviderKey")),
    responses: { "201": jsonResponse("Provider key summary", objectSchema("ProviderKeySummary")) },
    security: [{ bearerAuth: [] }],
    summary: "Store BYOK provider key",
    tags: ["byok"],
  },
  {
    method: "delete",
    operationId: "deleteProviderKey",
    path: "/v1/provider-keys/{provider}",
    responses: { "204": emptyResponse("Provider key deleted") },
    security: [{ bearerAuth: [] }],
    summary: "Delete BYOK provider key",
    tags: ["byok"],
  },
  ...billingRoutes,
  {
    method: "post",
    operationId: "recordClientError",
    path: "/v1/client-error",
    requestBody: jsonBody(objectSchema("ClientError")),
    responses: { "200": jsonResponse("Accepted", objectSchema("Ok")) },
    summary: "Record client error",
    tags: ["telemetry"],
  },
  {
    method: "post",
    operationId: "recordVitals",
    path: "/v1/vitals",
    requestBody: jsonBody(objectSchema("WebVitals")),
    responses: { "200": jsonResponse("Accepted", objectSchema("Ok")) },
    summary: "Record web vitals",
    tags: ["telemetry"],
  },
  {
    method: "post",
    operationId: "recordClientUserEvent",
    path: "/v1/user-events",
    requestBody: jsonBody(objectSchema("ClientUserEvent")),
    responses: { "200": jsonResponse("Accepted", objectSchema("Ok")) },
    security: [{ bearerAuth: [] }],
    summary: "Record authenticated UI activation event",
    tags: ["telemetry"],
  },
  {
    method: "get",
    operationId: "getOpenApiDocument",
    path: "/openapi.json",
    responses: { "200": jsonResponse("OpenAPI document", objectSchema("OpenApiDocument")) },
    summary: "Get OpenAPI document",
    tags: ["system"],
  },
  {
    method: "get",
    operationId: "getApiDocs",
    path: "/docs",
    responses: { "200": emptyResponse("HTML API documentation") },
    summary: "Get API docs",
    tags: ["system"],
  },
  {
    method: "get",
    operationId: "health",
    path: "/health",
    responses: { "200": jsonResponse("Health", objectSchema("Health")) },
    summary: "Health check",
    tags: ["system"],
  },
];

export const OPENAPI_DOCUMENT = buildOpenApiDocument({
  routes,
  schemas: {
    ...COMPONENT_SCHEMAS,
    ...accountSchemas,
    ...billingSchemas,
    ...discoverySchemas,
    ...runControlSchemas,
    ...sandboxSchemas,
  },
});

export const openApiDocsHtml = (): string => renderOpenApiDocsHtml(routes);
