import {
  BrowserTakeoverResumeResultSchema,
  BrowserTakeoverResumeSchema,
  BrowserTakeoverSessionSchema,
  BrowserTakeoverStatusSchema,
  SandboxConsoleSnapshotSchema,
  SandboxFileListSchema,
  SandboxFilePreviewSchema,
  SandboxFileSchema,
  SandboxFileWriteSchema,
  SandboxIdeSessionSchema,
  SandboxPreviewStatusSchema,
  SandboxPreviewWakeSchema,
  SandboxTerminalCommandSchema,
  SandboxTerminalContextSchema,
  SandboxTerminalResultSchema,
  UpdateSandboxPathFileSchema,
} from "@cheatcode/types";
import {
  type JsonValue,
  jsonBody,
  jsonResponse,
  type OpenApiRoute,
  schemaRef,
} from "./openapi-builder";
import { zodJsonSchema } from "./openapi-zod";

export const sandboxSchemas: Record<string, JsonValue> = {
  BrowserTakeoverResume: zodJsonSchema(BrowserTakeoverResumeSchema, "input"),
  BrowserTakeoverResumeResult: zodJsonSchema(BrowserTakeoverResumeResultSchema),
  BrowserTakeoverSession: zodJsonSchema(BrowserTakeoverSessionSchema),
  BrowserTakeoverStatus: zodJsonSchema(BrowserTakeoverStatusSchema),
  OpenSandboxTerminal: zodJsonSchema(SandboxTerminalCommandSchema, "input"),
  SandboxConsoleSnapshot: zodJsonSchema(SandboxConsoleSnapshotSchema),
  SandboxFile: zodJsonSchema(SandboxFileSchema),
  SandboxFileList: zodJsonSchema(SandboxFileListSchema),
  SandboxFilePreview: zodJsonSchema(SandboxFilePreviewSchema),
  SandboxFileWrite: zodJsonSchema(SandboxFileWriteSchema),
  SandboxIdeSession: zodJsonSchema(SandboxIdeSessionSchema),
  SandboxPreviewStatus: zodJsonSchema(SandboxPreviewStatusSchema),
  SandboxPreviewWake: zodJsonSchema(SandboxPreviewWakeSchema),
  TerminalContext: zodJsonSchema(SandboxTerminalContextSchema),
  TerminalPreview: zodJsonSchema(SandboxTerminalResultSchema),
  WriteSandboxFile: zodJsonSchema(UpdateSandboxPathFileSchema, "input"),
};

const sandboxEncodingParameter: JsonValue = {
  in: "query",
  name: "encoding",
  schema: { enum: ["utf8", "base64"], type: "string" },
};

const sandboxFilePathParameter: JsonValue = {
  in: "query",
  name: "path",
  required: true,
  schema: {
    maxLength: 1_000,
    pattern: "^/workspace(?:/(?!\\.{1,2}(?:/|$))[^/\\u0000]+)*$",
    type: "string",
  },
};

const sandboxFileListParameters: JsonValue[] = [
  {
    in: "query",
    name: "path",
    schema: {
      default: "/workspace",
      maxLength: 1_000,
      pattern: "^/workspace(?:/(?!\\.{1,2}(?:/|$))[^/\\u0000]+)*$",
      type: "string",
    },
  },
  { in: "query", name: "recursive", schema: { default: true, type: "boolean" } },
  { in: "query", name: "includeHidden", schema: { default: false, type: "boolean" } },
];

export const sandboxRoutes: OpenApiRoute[] = [
  {
    method: "get",
    operationId: "getBrowserTakeoverStatus",
    path: "/v1/threads/{threadId}/browser-takeover",
    responses: {
      "200": jsonResponse("Browser takeover status", schemaRef("BrowserTakeoverStatus")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Read the active browser takeover state",
    tags: ["sandbox"],
  },
  {
    method: "post",
    operationId: "startBrowserTakeover",
    path: "/v1/threads/{threadId}/browser-takeover/start",
    responses: {
      "200": jsonResponse("Browser takeover session", schemaRef("BrowserTakeoverSession")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Pause automation and take over its live browser",
    tags: ["sandbox"],
  },
  {
    method: "post",
    operationId: "resumeBrowserAutomation",
    path: "/v1/threads/{threadId}/browser-takeover/resume",
    requestBody: jsonBody(schemaRef("BrowserTakeoverResume")),
    responses: {
      "200": jsonResponse("Browser automation resumed", schemaRef("BrowserTakeoverResumeResult")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Close human control and resume browser automation",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "openComputerIde",
    path: "/v1/computer/ide",
    responses: { "200": jsonResponse("Computer IDE session", schemaRef("SandboxIdeSession")) },
    security: [{ bearerAuth: [] }],
    summary: "Open the user's embedded Computer file viewer",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "readComputerTerminalContext",
    path: "/v1/computer/terminal/context",
    responses: { "200": jsonResponse("Terminal context", schemaRef("TerminalContext")) },
    security: [{ bearerAuth: [] }],
    summary: "Read the user's Computer terminal context",
    tags: ["sandbox"],
  },
  {
    method: "post",
    operationId: "openComputerTerminal",
    path: "/v1/computer/terminal",
    requestBody: jsonBody(schemaRef("OpenSandboxTerminal")),
    responses: { "200": jsonResponse("Terminal preview", schemaRef("TerminalPreview")) },
    security: [{ bearerAuth: [] }],
    summary: "Run a command in the user's Computer",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "readSandboxConsole",
    parameters: [
      {
        in: "query",
        name: "processId",
        schema: { default: "app-preview", maxLength: 200, minLength: 1, type: "string" },
      },
      { in: "query", name: "stdoutCursor", schema: { default: 0, minimum: 0, type: "integer" } },
      { in: "query", name: "stderrCursor", schema: { default: 0, minimum: 0, type: "integer" } },
      {
        in: "query",
        name: "lastPid",
        schema: { maxLength: 100, minLength: 1, type: "string" },
      },
      {
        in: "query",
        name: "tail",
        schema: { default: 200, maximum: 500, minimum: 1, type: "integer" },
      },
    ],
    path: "/v1/threads/{threadId}/sandbox/console",
    responses: {
      "200": jsonResponse("Sandbox console snapshot", schemaRef("SandboxConsoleSnapshot")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Tail dev-server console output for a thread's sandbox",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "listSandboxFiles",
    parameters: sandboxFileListParameters,
    path: "/v1/threads/{threadId}/sandbox/files",
    responses: { "200": jsonResponse("Sandbox files", schemaRef("SandboxFileList")) },
    security: [{ bearerAuth: [] }],
    summary: "List sandbox files for a thread",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "openSandboxIde",
    path: "/v1/threads/{threadId}/sandbox/ide",
    responses: { "200": jsonResponse("Sandbox IDE session", schemaRef("SandboxIdeSession")) },
    security: [{ bearerAuth: [] }],
    summary: "Open the thread's embedded Files viewer",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "getSandboxPreviewStatus",
    path: "/v1/threads/{threadId}/sandbox/preview/status",
    responses: {
      "200": jsonResponse("Sandbox preview state", schemaRef("SandboxPreviewStatus")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Get the thread's preview sandbox state",
    tags: ["sandbox"],
  },
  {
    method: "post",
    operationId: "wakeSandboxPreview",
    path: "/v1/threads/{threadId}/sandbox/preview/wake",
    responses: {
      "200": jsonResponse("Woken sandbox preview", schemaRef("SandboxPreviewWake")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Wake the thread's preview sandbox and dev server",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "readSandboxFile",
    parameters: [sandboxFilePathParameter, sandboxEncodingParameter],
    path: "/v1/threads/{threadId}/sandbox/file",
    responses: { "200": jsonResponse("Sandbox file", schemaRef("SandboxFile")) },
    security: [{ bearerAuth: [] }],
    summary: "Read a sandbox file by path",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "previewSandboxFile",
    parameters: [sandboxFilePathParameter],
    path: "/v1/threads/{threadId}/sandbox/file-preview",
    responses: { "200": jsonResponse("Sandbox file preview", schemaRef("SandboxFilePreview")) },
    security: [{ bearerAuth: [] }],
    summary: "Preview a sandbox file by path",
    tags: ["sandbox"],
  },
  {
    method: "patch",
    operationId: "writeSandboxFile",
    path: "/v1/threads/{threadId}/sandbox/file",
    requestBody: jsonBody(schemaRef("WriteSandboxFile")),
    responses: { "200": jsonResponse("Sandbox file write", schemaRef("SandboxFileWrite")) },
    security: [{ bearerAuth: [] }],
    summary: "Write a sandbox file by path",
    tags: ["sandbox"],
  },
  {
    method: "get",
    operationId: "readSandboxTerminalContext",
    path: "/v1/threads/{threadId}/sandbox/terminal/context",
    responses: { "200": jsonResponse("Terminal context", schemaRef("TerminalContext")) },
    security: [{ bearerAuth: [] }],
    summary: "Read sandbox terminal prompt context",
    tags: ["sandbox"],
  },
  {
    method: "post",
    operationId: "openSandboxTerminal",
    path: "/v1/threads/{threadId}/sandbox/terminal",
    requestBody: jsonBody(schemaRef("OpenSandboxTerminal")),
    responses: { "200": jsonResponse("Terminal preview", schemaRef("TerminalPreview")) },
    security: [{ bearerAuth: [] }],
    summary: "Run a sandbox terminal command",
    tags: ["sandbox"],
  },
];
