import {
  CreateProjectSchema,
  CreateThreadSchema,
  ProjectSummarySchema,
  ThreadSchema,
  UIMessageRecordSchema,
  UpdateProjectSchema,
  UpdateThreadSchema,
} from "@cheatcode/types";
import {
  contentResponse,
  emptyResponse,
  type JsonValue,
  jsonBody,
  jsonResponse,
  type OpenApiRoute,
  schemaRef,
} from "./openapi-builder";
import { paginatedSchemaFor, paginationParameters } from "./openapi-schema-utils";
import { withJsonSchemaConstraints, zodJsonSchema } from "./openapi-zod";

export const projectSchemas: Record<string, JsonValue> = {
  CreateProject: zodJsonSchema(CreateProjectSchema, "input"),
  CreateThread: zodJsonSchema(CreateThreadSchema, "input"),
  Project: zodJsonSchema(ProjectSummarySchema),
  Thread: zodJsonSchema(ThreadSchema),
  UIMessage: zodJsonSchema(UIMessageRecordSchema),
  UpdateProject: withJsonSchemaConstraints(zodJsonSchema(UpdateProjectSchema, "input"), {
    minProperties: 1,
  }),
  UpdateThread: zodJsonSchema(UpdateThreadSchema, "input"),
};

const paginatedSchema = (name: string): JsonValue => paginatedSchemaFor(projectSchemas, name);

export const projectRoutes: OpenApiRoute[] = [
  {
    method: "get",
    operationId: "listProjects",
    parameters: paginationParameters,
    path: "/v1/projects",
    responses: { "200": jsonResponse("Projects", paginatedSchema("Project")) },
    security: [{ bearerAuth: [] }],
    summary: "List projects",
    tags: ["projects"],
  },
  {
    method: "post",
    operationId: "createProject",
    path: "/v1/projects",
    requestBody: jsonBody(schemaRef("CreateProject")),
    responses: { "201": jsonResponse("Created project", schemaRef("Project")) },
    security: [{ bearerAuth: [] }],
    summary: "Create a project",
    tags: ["projects"],
  },
  {
    method: "get",
    operationId: "getProject",
    path: "/v1/projects/{projectId}",
    responses: {
      "200": jsonResponse("Project", schemaRef("Project")),
      "404": jsonResponse("Not found", schemaRef("Error")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Get a project",
    tags: ["projects"],
  },
  {
    method: "patch",
    operationId: "updateProject",
    path: "/v1/projects/{projectId}",
    requestBody: jsonBody(schemaRef("UpdateProject")),
    responses: { "200": jsonResponse("Updated project", schemaRef("Project")) },
    security: [{ bearerAuth: [] }],
    summary: "Update a project",
    tags: ["projects"],
  },
  {
    method: "delete",
    operationId: "deleteProject",
    path: "/v1/projects/{projectId}",
    responses: { "202": emptyResponse("Project deletion accepted") },
    security: [{ bearerAuth: [] }],
    summary: "Delete a project",
    tags: ["projects"],
  },
  {
    method: "post",
    operationId: "downloadProject",
    path: "/v1/projects/{projectId}/download",
    responses: {
      "200": contentResponse("Project ZIP archive", "application/zip", {
        format: "binary",
        type: "string",
      }),
      "404": jsonResponse("Not found", schemaRef("Error")),
      "422": jsonResponse("Archive could not be prepared", schemaRef("Error")),
    },
    security: [{ bearerAuth: [] }],
    summary: "Download a project archive",
    tags: ["projects"],
  },
  {
    method: "get",
    operationId: "listProjectThreads",
    parameters: paginationParameters,
    path: "/v1/projects/{projectId}/threads",
    responses: { "200": jsonResponse("Threads", paginatedSchema("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "List project threads",
    tags: ["threads"],
  },
  {
    method: "post",
    operationId: "createThread",
    path: "/v1/threads",
    requestBody: jsonBody(schemaRef("CreateThread")),
    responses: { "201": jsonResponse("Created thread", schemaRef("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "Create a project-less or project-linked thread",
    tags: ["threads"],
  },
  {
    method: "get",
    operationId: "getThread",
    path: "/v1/threads/{threadId}",
    responses: { "200": jsonResponse("Thread", schemaRef("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "Get a thread",
    tags: ["threads"],
  },
  {
    method: "patch",
    operationId: "updateThread",
    path: "/v1/threads/{threadId}",
    requestBody: jsonBody(schemaRef("UpdateThread")),
    responses: { "200": jsonResponse("Updated thread", schemaRef("Thread")) },
    security: [{ bearerAuth: [] }],
    summary: "Update a thread",
    tags: ["threads"],
  },
  {
    method: "delete",
    operationId: "deleteThread",
    path: "/v1/threads/{threadId}",
    responses: { "202": emptyResponse("Thread deletion accepted") },
    security: [{ bearerAuth: [] }],
    summary: "Delete a thread",
    tags: ["threads"],
  },
  {
    method: "get",
    operationId: "listThreadMessages",
    parameters: paginationParameters,
    path: "/v1/threads/{threadId}/messages",
    responses: { "200": jsonResponse("Messages", paginatedSchema("UIMessage")) },
    security: [{ bearerAuth: [] }],
    summary: "List thread messages",
    tags: ["threads"],
  },
];
