import {
  mastraBrowserAct,
  mastraBrowserExtract,
  mastraBrowserObserve,
  mastraBrowserOpen,
  mastraBrowserScreenshot,
  mastraCompetitorResearch,
  mastraComposioExecute,
  mastraComposioListTools,
  mastraDataAnalyzeCsv,
  mastraDataChart,
  mastraDataScrapeToCsv,
  mastraDeepResearch,
  mastraDocsGenerateDocx,
  mastraDocsGeneratePdf,
  mastraDocsGenerateSlides,
  mastraDocsGenerateXlsx,
  mastraFirecrawlExtract,
  mastraFirecrawlScrape,
  mastraFirecrawlSearch,
  mastraFsDelete,
  mastraFsList,
  mastraFsRead,
  mastraFsSearch,
  mastraFsWrite,
  mastraGitClone,
  mastraGitCommit,
  mastraGitPush,
  mastraGitStatus,
  mastraResearchFanout,
  mastraRunCode,
  mastraSearchCompany,
  mastraSearchWeb,
  mastraSearchWebAdvanced,
  mastraShellExec,
  mastraShellKillProcess,
  mastraShellStartProcess,
  mastraShellTerminal,
  mastraSkillCreate,
  mastraSkillInvoke,
  mastraSkillReadReference,
  mastraStartDevServer,
} from "./registry";

export const cheatcodeTools = {
  browser_act: mastraBrowserAct,
  browser_extract: mastraBrowserExtract,
  browser_observe: mastraBrowserObserve,
  browser_open: mastraBrowserOpen,
  browser_screenshot: mastraBrowserScreenshot,
  composio_execute: mastraComposioExecute,
  composio_list_tools: mastraComposioListTools,
  data_analyze_csv: mastraDataAnalyzeCsv,
  data_chart: mastraDataChart,
  data_scrape_to_csv: mastraDataScrapeToCsv,
  docs_generate_docx: mastraDocsGenerateDocx,
  docs_generate_pdf: mastraDocsGeneratePdf,
  docs_generate_slides: mastraDocsGenerateSlides,
  docs_generate_xlsx: mastraDocsGenerateXlsx,
  firecrawl_extract: mastraFirecrawlExtract,
  firecrawl_scrape: mastraFirecrawlScrape,
  firecrawl_search: mastraFirecrawlSearch,
  fs_delete: mastraFsDelete,
  fs_list: mastraFsList,
  fs_read: mastraFsRead,
  fs_search: mastraFsSearch,
  fs_write: mastraFsWrite,
  git_clone: mastraGitClone,
  git_commit: mastraGitCommit,
  git_push: mastraGitPush,
  git_status: mastraGitStatus,
  research_competitor: mastraCompetitorResearch,
  research_deep: mastraDeepResearch,
  research_fanout: mastraResearchFanout,
  runCode: mastraRunCode,
  search_company: mastraSearchCompany,
  search_web: mastraSearchWeb,
  search_web_advanced: mastraSearchWebAdvanced,
  shell_exec: mastraShellExec,
  shell_kill_process: mastraShellKillProcess,
  shell_start_process: mastraShellStartProcess,
  shell_terminal: mastraShellTerminal,
  skill_create: mastraSkillCreate,
  skill_invoke: mastraSkillInvoke,
  skill_read_reference: mastraSkillReadReference,
  start_dev_server: mastraStartDevServer,
} as const;
