// AUTO-GENERATED by scripts/build-skills.ts. Do not edit.
import type { SkillManifestEntry } from "./types";

export const SKILL_MANIFEST: SkillManifestEntry[] = [
  {
    "name": "competitor-brief",
    "description": "Creates concise competitor intelligence briefs with positioning, pricing, product surface, traction, and risks. Use when the user asks for competitor research, company intel, alternatives, or competitive landscape. Do NOT trigger for generic news digests.",
    "category": "Research & Docs",
    "tags": [
      "research",
      "competitive analysis",
      "market"
    ]
  },
  {
    "name": "csv-analyst",
    "description": "Analyzes CSV or spreadsheet data with statistics, charts, joins, and clear findings. Use when the user uploads CSV/XLSX data or asks for data analysis, cohort analysis, charts, or spreadsheet insight. Do NOT trigger for document-only research.",
    "category": "Data & Media",
    "tags": [
      "data",
      "csv",
      "analysis",
      "charts"
    ]
  },
  {
    "name": "deep-research",
    "description": "Produces a cited long-form research report on a complex question, fanning out parallel research probes when the topic spans many entities or angles. Use when the user asks for deep research, a cited report, market analysis, due diligence, a broad market scan, or a comprehensive investigation. Do NOT trigger for quick factual lookups.",
    "category": "Research & Docs",
    "tags": [
      "research",
      "report",
      "analysis"
    ]
  },
  {
    "name": "landing-page",
    "description": "Builds production-quality landing pages or app marketing pages from an offer, product, or audience. Use when the user asks for a landing page, homepage, SaaS page, launch page, or conversion page. Do NOT trigger for full app dashboards.",
    "category": "Builder & Apps",
    "tags": [
      "web",
      "landing page",
      "marketing"
    ]
  },
  {
    "name": "mobile-app",
    "description": "Builds the mobile app experience for the current project — Expo Router screens in mobile (app-builder-mobile) projects, mobile-first responsive web surfaces in web projects. Use when the user asks for a mobile app, iPhone-like app, mobile-first builder, or responsive app prototype. Do NOT trigger for App Store or Play Store release builds in V1.",
    "category": "Builder & Apps",
    "tags": [
      "mobile",
      "app",
      "expo"
    ]
  },
  {
    "name": "pitch-deck",
    "description": "Generates investor-ready pitch decks from a one-line startup idea or written brief. Use when the user asks for a pitch deck, investor deck, fundraising deck, demo day deck, seed deck, or .pptx deck. Do NOT trigger for internal PRD slides; use slide-from-prd.",
    "category": "Research & Docs",
    "tags": [
      "slides",
      "fundraising",
      "investor"
    ]
  },
  {
    "name": "slide-from-prd",
    "description": "Turns a PRD, roadmap, memo, or internal product brief into clear presentation slides. Use when the user asks for product update slides, roadmap slides, executive slides, or a PRD-to-deck conversion. Do NOT trigger for fundraising decks; use pitch-deck.",
    "category": "Research & Docs",
    "tags": [
      "slides",
      "prd",
      "product"
    ]
  },
  {
    "name": "social-post-pack",
    "description": "Creates platform-specific social posts, hooks, image prompts, and variants from a launch, report, or announcement. Use when the user asks for LinkedIn posts, X/Twitter threads, social copy, carousels, or launch content. Do NOT trigger for long-form reports.",
    "category": "Data & Media",
    "tags": [
      "social",
      "content",
      "marketing"
    ]
  }
];
