import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type BundledSkill,
  SKILL_CATEGORIES,
  type SkillCategory,
  type SkillManifestEntry,
} from "../packages/skills/src/types";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SKILLS_DIR = join(REPO_ROOT, "skills");
const OUT = join(REPO_ROOT, "packages/skills/src/generated.ts");
const MANIFEST_OUT = join(REPO_ROOT, "packages/skills/src/generated-manifest.ts");

interface FrontmatterResult {
  data: Record<string, string>;
  body: string;
}

function parseFrontmatter(raw: string): FrontmatterResult {
  if (!raw.startsWith("---\n")) {
    throw new Error("SKILL.md must start with YAML frontmatter");
  }
  const end = raw.indexOf("\n---\n", 4);
  if (end === -1) {
    throw new Error("SKILL.md frontmatter must end with ---");
  }
  const frontmatter = raw.slice(4, end);
  const body = raw.slice(end + "\n---\n".length);
  const data: Record<string, string> = {};

  let currentKey: string | undefined;
  for (const line of frontmatter.split("\n")) {
    if (/^\s+/.test(line) && currentKey) {
      data[currentKey] = `${data[currentKey]}\n${line.trim()}`;
      continue;
    }
    const separator = line.indexOf(":");
    if (separator === -1) {
      continue;
    }
    currentKey = line.slice(0, separator).trim();
    data[currentKey] = line
      .slice(separator + 1)
      .trim()
      .replace(/^["']|["']$/g, "");
  }

  return { data, body };
}

function parseCategory(slug: string, raw: string | undefined): SkillCategory {
  if (!raw) {
    throw new Error(`${slug}/SKILL.md requires a category frontmatter field`);
  }
  const match = SKILL_CATEGORIES.find((category) => category === raw);
  if (!match) {
    throw new Error(
      `${slug}/SKILL.md category "${raw}" must be one of: ${SKILL_CATEGORIES.join(", ")}`,
    );
  }
  return match;
}

function parseTags(raw: string | undefined): string[] {
  if (!raw) {
    return [];
  }
  return raw
    .split(",")
    .map((tag) => tag.trim())
    .filter((tag) => tag.length > 0);
}

const BUNDLED_TEXT_EXTENSIONS = new Set([".md", ".txt", ".json", ".yaml", ".yml"]);

function readTextFiles(dir: string): Record<string, string> {
  if (!existsSync(dir)) {
    return {};
  }

  const files: Array<[string, string]> = [];
  const visit = (current: string): void => {
    for (const entry of readdirSync(current).sort()) {
      const absolutePath = join(current, entry);
      const stat = statSync(absolutePath);
      if (stat.isDirectory()) {
        visit(absolutePath);
        continue;
      }
      if (!stat.isFile()) {
        continue;
      }
      const extension = entry.includes(".") ? `.${entry.split(".").pop()?.toLowerCase()}` : "";
      if (!BUNDLED_TEXT_EXTENSIONS.has(extension)) {
        continue;
      }
      const relativePath = relative(dir, absolutePath).split(sep).join("/");
      files.push([relativePath, readFileSync(absolutePath, "utf8")]);
    }
  };

  visit(dir);
  return Object.fromEntries(files);
}

function bundleSkill(slug: string): BundledSkill {
  const skillDir = join(SKILLS_DIR, slug);
  const raw = readFileSync(join(skillDir, "SKILL.md"), "utf8");
  const { data, body } = parseFrontmatter(raw);
  const name = data["name"];
  const description = data["description"];
  if (!name || !description) {
    throw new Error(`${slug}/SKILL.md requires name and description`);
  }
  const bundledSkill: BundledSkill = {
    name,
    description,
    category: parseCategory(slug, data["category"]),
    tags: parseTags(data["tags"]),
    metadata: {},
    body,
    references: readTextFiles(join(skillDir, "references")),
    assets: readTextFiles(join(skillDir, "assets")),
  };
  const license = data["license"];
  if (license) {
    bundledSkill.license = license;
  }
  const compatibility = data["compatibility"];
  if (compatibility) {
    bundledSkill.compatibility = compatibility;
  }
  return bundledSkill;
}

const skills = readdirSync(SKILLS_DIR)
  .filter((slug) => statSync(join(SKILLS_DIR, slug)).isDirectory())
  .sort()
  .map(bundleSkill);

const manifest: SkillManifestEntry[] = skills.map((skill) => ({
  name: skill.name,
  description: skill.description,
  category: skill.category,
  tags: skill.tags,
}));

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  [
    "// AUTO-GENERATED by scripts/build-skills.ts. Do not edit.",
    'import type { BundledSkill } from "./types";',
    "",
    `export const SKILLS: BundledSkill[] = ${JSON.stringify(skills, null, 2)};`,
    "",
  ].join("\n"),
);

writeFileSync(
  MANIFEST_OUT,
  [
    "// AUTO-GENERATED by scripts/build-skills.ts. Do not edit.",
    'import type { SkillManifestEntry } from "./types";',
    "",
    `export const SKILL_MANIFEST: SkillManifestEntry[] = ${JSON.stringify(manifest, null, 2)};`,
    "",
  ].join("\n"),
);

console.info(`Bundled ${skills.length} skills into ${OUT} and ${MANIFEST_OUT}`);
