import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BundledSkill } from "../packages/skills/src/types";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SKILLS_DIR = join(REPO_ROOT, "skills");
const OUT = join(REPO_ROOT, "packages/skills/src/generated.ts");

interface FrontmatterResult {
  data: Record<string, string>;
  body: string;
}

function parseFrontmatter(raw: string): FrontmatterResult {
  if (!raw.startsWith("---\n")) {
    throw new Error("SKILL.md must start with YAML frontmatter");
  }
  const end = raw.indexOf("\n---\n", 4);
  if (end === -1) {
    throw new Error("SKILL.md frontmatter must end with ---");
  }
  const frontmatter = raw.slice(4, end);
  const body = raw.slice(end + "\n---\n".length);
  const data: Record<string, string> = {};

  let currentKey: string | undefined;
  for (const line of frontmatter.split("\n")) {
    if (/^\s+/.test(line) && currentKey) {
      data[currentKey] = `${data[currentKey]}\n${line.trim()}`;
      continue;
    }
    const separator = line.indexOf(":");
    if (separator === -1) {
      continue;
    }
    currentKey = line.slice(0, separator).trim();
    data[currentKey] = line
      .slice(separator + 1)
      .trim()
      .replace(/^["']|["']$/g, "");
  }

  return { data, body };
}

function readTextFiles(dir: string): Record<string, string> {
  if (!existsSync(dir)) {
    return {};
  }
  return Object.fromEntries(
    readdirSync(dir)
      .filter((file) => statSync(join(dir, file)).isFile())
      .map((file) => [file, readFileSync(join(dir, file), "utf8")]),
  );
}

function bundleSkill(slug: string): BundledSkill {
  const skillDir = join(SKILLS_DIR, slug);
  const raw = readFileSync(join(skillDir, "SKILL.md"), "utf8");
  const { data, body } = parseFrontmatter(raw);
  const name = data["name"];
  const description = data["description"];
  if (!name || !description) {
    throw new Error(`${slug}/SKILL.md requires name and description`);
  }
  const bundledSkill: BundledSkill = {
    name,
    description,
    metadata: {},
    body,
    references: readTextFiles(join(skillDir, "references")),
    assets: readTextFiles(join(skillDir, "assets")),
  };
  const license = data["license"];
  if (license) {
    bundledSkill.license = license;
  }
  const compatibility = data["compatibility"];
  if (compatibility) {
    bundledSkill.compatibility = compatibility;
  }
  return bundledSkill;
}

const skills = readdirSync(SKILLS_DIR)
  .filter((slug) => statSync(join(SKILLS_DIR, slug)).isDirectory())
  .sort()
  .map(bundleSkill);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  [
    "// AUTO-GENERATED by scripts/build-skills.ts. Do not edit.",
    'import type { BundledSkill } from "./types";',
    "",
    `export const SKILLS: BundledSkill[] = ${JSON.stringify(skills, null, 2)};`,
    "",
  ].join("\n"),
);

console.info(`Bundled ${skills.length} skills into ${OUT}`);
